// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.IntegrationTests.Fixtures;
using Content.Trauma.Shared.Forging;
using Robust.Shared.GameObjects;
using Robust.Shared.Prototypes;
using System.Collections.Generic;

namespace Content.IntegrationTests.Tests._Trauma;

public sealed class ForgingTest : GameTest
{
    /// <summary>
    /// Checks that all forged item prototypes are sane and that there are no empty categories.
    /// </summary>
    [Test]
    public async Task AllForgedItemsValid()
    {
        var pair = Pair;
        var server = pair.Server;

        var entMan = server.EntMan;
        var proto = server.ProtoMan;
        var factory = entMan.ComponentFactory;
        var metallicName = factory.GetComponentName<MetallicComponent>();
        await server.WaitAssertion(() =>
        {
            Assert.Multiple(() =>
            {
                var used = new HashSet<ProtoId<ForgingCategoryPrototype>>();
                // sanity check each item prototype
                foreach (var item in proto.EnumeratePrototypes<ForgedItemPrototype>())
                {
                    used.Add(item.Category);

                    if (item.Result is {} result)
                    {
                        var entity = proto.Index(result);
                        Assert.That(entity.Components.ContainsKey(metallicName),
                            $"Result of forging {item.ID}, {result}, must inherit from BaseMetallic!");
                    }
                    else if (item.Sprite != null)
                    {
                        Assert.That(item.Name, Is.Not.EqualTo(string.Empty), $"Forged item {item.ID} must set a name since it is procedurally generated!");
                        if (item.Construction != null)
                        {
                            Assert.That(item.Finished, Is.Not.Null, $"Forged item {item.ID} must have a finished item for its procedural construction graph!");
                        }
                    }
                    else
                    {
                        Assert.Fail($"Result of forging {item.ID} must either be procedurally generated by sprite or a specified result entity!");
                    }
                }

                // now check that all categories are used, i.e. not empty
                foreach (var category in proto.EnumeratePrototypes<ForgingCategoryPrototype>())
                {
                    Assert.That(used.Contains(category.ID), $"Forging category {category.ID} is not used by any items!");
                }
            });
        });
    }

    // TODO: test to spawn every material + item combination and simulate working them so theres no errors and check all sprites are valid
}
